# Generated by Django 4.0.5 on 2022-06-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=50)),
                ('task', models.CharField(max_length=50)),
                ('deadline', models.CharField(max_length=50)),
                ('team_member', models.CharField(max_length=50)),
                ('comments', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
