# Generated by Django 4.0.5 on 2022-07-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_work_delete_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='shift_timing',
            field=models.CharField(choices=[('DT', 'Day time'), ('NT', 'Night time')], default='DT', max_length=20),
        ),
    ]
