# Generated by Django 4.0.5 on 2022-07-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_work_shift_timing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='shift_timing',
            field=models.CharField(choices=[('Day Time', 'Day time'), ('NT Time', 'Night time')], default='Day Time', max_length=20),
        ),
    ]
