# Generated by Django 4.0.5 on 2022-07-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_work_shift_timing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='deadline',
            field=models.DateField(max_length=50),
        ),
    ]
