# Generated by Django 4.0.5 on 2022-07-07 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_work_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='deadline',
        ),
    ]
