# Generated by Django 4.0.5 on 2022-07-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_work_shift_timing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='shift_timing',
            field=models.CharField(choices=[('Day Time', 'Day Time'), ('Night Time', 'Night Time')], default='Day Time', max_length=20),
        ),
    ]
